# vi docker-compose.yml
version: '3.3'
services:
  mongoDBOrders:
    ports:
      - '27018:27017'
    container_name: dkrcomp-mongo2
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo